apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgreproduct-pv-volume
  namespace: eshop
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgreproduct-pv-claim
  namespace: eshop
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgreproduct
  namespace: eshop
spec:
  ports:
  - port: 5432
  selector:
    app: postgreproduct
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgreproduct
  namespace: eshop
spec:
  selector:
    matchLabels:
      app: postgreproduct
  serviceName: "postgreproduct"
  template:
    metadata:
      labels:
        app: postgreproduct
    spec:
      containers:
      - image: postgres:latest
        name: postgreproduct
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/some_name/
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: secretpostgreproduct
              key: USERNAME
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secretpostgreproduct
              key: PASSWORD
        - name: POSTGRES_DB
          value: product
        ports:
        - containerPort: 5432
          name: postgreproduct
        volumeMounts:
        - name: postgreproduct-persistent-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgreproduct-persistent-storage
        persistentVolumeClaim:
          claimName: postgreproduct-pv-claim