apiVersion: v1
kind: Service
metadata:
  name: order
  namespace: eshop
spec:
  ports:
  - port: 8080
  selector:
    app: order
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  namespace: eshop
spec:
  selector:
    matchLabels:
      app: order
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: order
    spec:
      volumes:
      - name: keys-v
        secret:
          secretName: keys
          defaultMode: 0600 
      containers:
      - image: nannuzzi/order:0.0.3
        name: order
        env:
        - name: spring.datasource.url
          value: jdbc:postgresql://postgreorder/order
        - name: spring.datasource.username
          valueFrom:
            secretKeyRef:
              name: secretpostgreorder
              key: USERNAME
        - name: spring.datasource.password
          valueFrom:
            secretKeyRef:
              name: secretpostgreorder
              key: PASSWORD
        - name: product_service_url
          value: http://product:8080
        ports:
        - containerPort: 8080
          name: order
        volumeMounts:
        - name: keys-v
          readOnly: true
          mountPath: "/etc/keys"