apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: eshop
spec:
  ports:
  - port: 8080
  selector:
    app: user
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: eshop
spec:
  selector:
    matchLabels:
      app: user
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: user
    spec:
      volumes:
      - name: keys-v
        secret:
          secretName: keys
          defaultMode: 0600 
      containers:
      - image: nannuzzi/user:0.0.3
        name: user
        env:
        - name: spring.datasource.url
          value: jdbc:mysql://mysql/user
        - name: spring.datasource.password
          valueFrom:
            secretKeyRef:
              name: secretmysql
              key: ROOT_PASSWORD
        volumeMounts:
        - name: keys-v
          readOnly: true
          mountPath: "/etc/keys"