apiVersion: v1
data:
  private.key: MIIB3QIBADANBgkqhkiG9w0BAQEFAASCAccwggHDAgEAAl8KGZpso3r/oWFNYeYVCItfyHQlRqfsKPQkxkEfUMkVqIRAsDKHiC/v9VpB2zGJn2LoGf5QzFXZltbb7kwuwQbeWd9eOfkps1z8Odn+TGADj2w0ms4sQQa4TdoTGSYK+wIDAQABAl4hclwYFXNOXbqMrgRh7zJtoio85mG0x+qJYTE5vf45ZIZp2+ScCwz5/PPeFT53QBLECugjKf70ZAgD+b4B2P8kOsFClAns+lWsq8uSGmoYB6iGiiYlwjmILKjxMt+xAjAC9It9XzzgM8v1IrRZNoqb1MYqJFFn355IoxFDh7oR+OZ/BN65iW2+GZEK1cbxjosCMANq6ucmh8jO5xIxfUmtLtbTwAfXnXEyqZognX/ipU8SWSrZTcGdniKNuzJlnH7zUQIwArK1777V23Qu0B3hPlo3blJyoeMKl6Vn47VNe7QdQ29VMb6GgipgkWDSNWw7+CpFAjACM2i/n61TIAHnUl1HA7Ik/0krA6tMiP501Un3X6FqcPtgv3z2EKUTxUdmJc8IZXECMAFDQRk0KTfWv+5TB8qBkIe08FyEKSLrzTswf9+dtxtjPJKXEVr/NnThIhSLRunW4g==
  public.key: MHowDQYJKoZIhvcNAQEBBQADaQAwZgJfChmabKN6/6FhTWHmFQiLX8h0JUan7Cj0JMZBH1DJFaiEQLAyh4gv7/VaQdsxiZ9i6Bn+UMxV2ZbW2+5MLsEG3lnfXjn5KbNc/DnZ/kxgA49sNJrOLEEGuE3aExkmCvsCAwEAAQ==
kind: Secret
metadata:
  name: keys
  namespace: eshop
type: Opaque